// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import search_controller from "./search_controller"
application.register("search", search_controller)

import admin_controller from "./admin_controller"
application.register("admin", admin_controller)

